swagger: '2.0'
info:
  title: XSS test
  description: |
    <math><mtext><h1><a><h6></a></h6><mglyph><svg><mtext><textarea>
    <a title='</textarea><img src onerror=alert("Hello")>'></textarea>
    </h1>">"</textarea></desc></textarea></mtext></mtext></svg></mglyph>
    </option></mtext></math>
  version: production
paths:
  /test:
    get:
      responses:
        '200':
          description: Test endpoint
